version: '3.8'

services:
  mysql:
    image: ghcr.io/r0n1n0/mysql:latest
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=${DB_DATABASE}
    networks:
      osa-network:
        aliases:
          - mysql
        ipv4_address: 192.168.176.2
    volumes:
     - db_data:/var/lib/mysql

  nodejs:
    image: ghcr.io/r0n1n0/nodejs:latest
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=mysql
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - TOKEN_SECRET=${TOKEN_SECRET}
    depends_on:
      - mysql
    networks:
      osa-network:
        aliases:
          - nodejs
        ipv4_address: 192.168.176.3

  nginx:
    image: ghcr.io/r0n1n0/nginx:latest
    ports:
      - '80:80'
    depends_on:
      - nodejs
      - mysql
    networks:
      osa-network:
        aliases:
          - nginx
        ipv4_address: 192.168.176.4

volumes:
  db_data:
    name: "db_data"
    external: false

networks:
  osa-network:
    driver: bridge
    name: osa-network
    ipam:
      config:
        - subnet: "192.168.176.0/20"
          gateway: "192.168.176.1"
