version: '3.8'

services:
  mysql:
    build:
      context: ./Database
      dockerfile: ./mysql.Dockerfile
    environment:
      - MYSQL_USER=bassou
      - MYSQL_PASSWORD=${DB_PASSWORD_RAW}
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=db_proyect
    networks:
      osa-network:
        aliases:
          - mysql
        ipv4_address: 192.168.176.2
    volumes:
     - db_data:/var/lib/mysql

  nodejs:
    build:
      context: ./Backend
      dockerfile: nodejs.Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=mysql
      - DB_USER=bassou
      - DB_DATABASE=db_proyect
      - DB_PASSWORD=${DB_PASSWORD}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - CLOUD_NAME=${CLOUD_NAME}
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
      - ENCRYPTION_SECRET=${ENCRYPTION_SECRET}
    depends_on:
      - mysql
    networks:
      osa-network:
        aliases:
          - nodejs
        ipv4_address: 192.168.176.3
  nginx:
    build:
      context: ./Frontend
      dockerfile: ./nginx.Dockerfile 
    ports:
      - '80:80'
    depends_on:
      - nodejs
      - mysql
    networks:
      osa-network:
        aliases:
          - nginx
        ipv4_address: 192.168.176.4

volumes:
  db_data:
    name: "db_data"
    external: false

networks:
  osa-network:
    driver: bridge
    name: osa-network
    ipam:
      config:
        - subnet: "192.168.176.0/20"
          gateway: "192.168.176.1"
