version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: mysql.Dockerfile
    ports:
      - '3306:3306'
    environment:
      - MYSQL_USER=bassou
      - MYSQL_PASSWORD=1234
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=db_proyect
    volumes:
     - db_data:/var/lib/mysql
    networks:
      osa-network:
        aliases:
          - mysql
        ipv4_address: 192.168.176.2

  nodejs:
    build:
      context: .
      dockerfile: nodejs.Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=mysql:3306
      - DB_USER=bassou
      - DB_PASSWORD=1234
      - DB_DATABASE=db_proyect
      - TOKEN_SECRET=9b68a78a1164c77b42f2bb026f047d49
    depends_on:
      - mysql
    networks:
      osa-network:
        aliases:
          - nodejs
        ipv4_address: 192.168.176.3

  nginx:
    image: nginx:1.25.4-alpine
    ports:
      - '80:80'
    volumes:
      - ./Frontend:/usr/share/nginx/html
      - ./conf:/etc/nginx/conf.d
      - nginx_logs:/var/log/nginx
    depends_on:
      - nodejs
      - mysql
    networks:
      osa-network:
        aliases:
          - nginx
        ipv4_address: 192.168.176.4

volumes:
  nginx_logs:
    external: true
  db_data:
    external: true

networks:
  osa-network:
    driver: bridge
    name: osa-network
    ipam:
      config:
        - subnet: "192.168.176.0/20"
          gateway: "192.168.176.1"
