version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    volumes:
      - ../Frontend:/var/www/html
    depends_on:
      - backend
      - db

  backend:
    build:
      context: .
      dockerfile: nodejs.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  db:
    image: mysql:latest
    environment:
      MYSQL_USER: bassou
      MYSQL_PASSWORD: 1234
      MYSQL_ALLOW_EMPTY_PASSWORD: no
    volumes:
    - ./Backend/db/db_project.sql:/docker-entrypoint-initdb.d/dump.sql
     - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
    external: true
