apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    spec.ingressClassName: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - osaproject.es
        - www.osaproject.es
      secretName: ssl
    - hosts:
        - nodejs.osaproject.es
      secretName: ssl-node
  rules:
  - host: "www.osaproject.es"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginx-service
            port:
              number: 80
  - host: "nodejs.osaproject.es"
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: nodejs-service
              port:
                number: 80
  - host: nodejs.osaproject.es
    http:
      paths:
        - path: /.well-known/acme-challenge/
          pathType: Prefix
          backend:
            service:
              name: nodejs-service
              port:
                number: 80