apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: osaproject.es
    http:
      paths:
      - path: /nginx
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
      - path: /nodejs
        pathType: Prefix
        backend:
          service:
            name: nodejs-service
            port:
              number: 3000
