apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: registry.digitalocean.com/osa-containerregistry/nodejs:latest
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m" 
        ports:
        - containerPort: 3000
        env:
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: DB_DATABASE
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: DB_USER
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: DB_PORT
          # secrets
        - name: DB_PASSWORD1
          valueFrom:
            secretKeyRef:
              name: backendsecrets
              key: DB_PASSWORD1
        - name: DB_PASSWORD2
          valueFrom:
            secretKeyRef:
              name: backendsecrets
              key: DB_PASSWORD2
        - name: TOKEN_SECRET1
          valueFrom:
            secretKeyRef:
              name: backendsecrets
              key: TOKEN_SECRET1
        - name: TOKEN_SECRET2
          valueFrom:
            secretKeyRef:
              name: backendsecrets
              key: TOKEN_SECRET2
        - name: CLOUD_NAME
          valueFrom:
            secretKeyRef:
              name: backendsecrets
              key: CLOUD_NAME
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: backendsecrets
              key: API_KEY
        - name: API_SECRET1
          valueFrom:
            secretKeyRef:
              name: backendsecrets
              key: API_SECRET1
        - name: API_SECRET2
          valueFrom:
            secretKeyRef:
              name: backendsecrets
              key: API_SECRET2