name: main-publish

on:
  push:
    branches: ["main"]

env:
  REPO: registry.digitalocean.com/osa-containerregistry
  TAG: ${{ github.workflow_sha }}

jobs:
  nginx:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
        id-token: write

    steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - uses: actions/checkout@v3
        - name: Build the Docker image
          run: |
            docker build ./Frontend --file ./Frontend/nginx.Dockerfile --tag nginx:${{ env.TAG }} --tag nginx:latest

        - name: Login with Docker
          run: |
            docker login registry.digitalocean.com -u ${{ secrets.DOCR_USER }} -p ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
        - name: Prepare images to push
          run: |
            docker tag nginx:latest ${{ env.REPO }}/nginx:latest
            docker tag nginx:${{ env.TAG }} ${{ env.REPO }}/nginx:${{ env.TAG }}

        - name: Push Docker image to DigitalOcean Container Registry
          run: |
            docker push ${{ env.REPO }}/nginx:latest
            docker push ${{ env.REPO }}/nginx:${{ env.TAG }}
            
  nodejs:
    runs-on: ubuntu-latest
    needs: nginx
    permissions:
      contents: read
      packages: write
      id-token: write
          
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker build ./Backend --file ./Backend/nodejs.Dockerfile --quiet --tag nodejs:${{ env.TAG }} --tag nodejs:latest --build-arg ENCRYPTION_KEY="${{ secrets.ENCRYPTION_KEY }}"

      - name: Login with Docker
        run: |
          docker login registry.digitalocean.com -u ${{ secrets.DOCR_USER }} -p ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Prepare images to push
        run: |
          docker tag nodejs:latest ${{ env.REPO }}/nodejs:latest
          docker tag nodejs:${{ env.TAG }} ${{ env.REPO }}/nodejs:${{ env.TAG }}

      - name: Push Docker image to DigitalOcean Container Registry
        run: |
          docker push ${{ env.REPO }}/nodejs:latest
          docker push ${{ env.REPO }}/nodejs:${{ env.TAG }}